# Generated by Django 4.0.1 on 2022-05-29 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_founditem_user_lostitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='user',
        ),
        migrations.AddField(
            model_name='founditem',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
